/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            // The newInstance() call is a work around for some
            // broken Java implementations

            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        } catch (Exception ex) {
            // handle the error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Register_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage());
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 50, 90, 20);

        Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Username);
        Username.setBounds(140, 50, 220, 30);

        Pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel1.add(Pass);
        Pass.setBounds(140, 140, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 80, 20);

        Register_Button.setBackground(new java.awt.Color(0, 102, 102));
        Register_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Register_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Register_Button);
        Register_Button.setBounds(10, 340, 120, 40);

        Login_Button.setBackground(new java.awt.Color(0, 102, 102));
        Login_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Login_Button);
        Login_Button.setBounds(310, 340, 120, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 450, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        
        if (Username.getText().isEmpty() || Pass.getText().isEmpty()){
            JOptionPane.showMessageDialog(Login_Button, "Username and password cannnot be empty.");
        }
        else if ("1".equals(Username.getText()) && "1".equals(Pass.getText())){
            pharmacist ah = new pharmacist();
            ah.setVisible(true);
            dispose();
            return;
        }
        else if ("2".equals(Username.getText()) && "2".equals(Pass.getText())){
            service ah = new service();
            ah.setVisible(true);
            dispose();
            return;
        }
        else{
            String userName, pass;
            userName = Username.getText();
            pass = Pass.getText();
            //pharmacy & store login

            //patient login
            Connection c = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            try { 
                 c = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                                + "user=root&password=root");
                 String sql= "Select Patient_UserName, Patient_Password, idpatient from patient where Patient_UserName=? and Patient_Password=?";
                  ps = c.prepareStatement(sql);
                        ps.setString(1, userName);
                        ps.setString(2, pass);
                        rs = ps.executeQuery();
                        if (rs.next()) {
                            String patientID = rs.getString("idpatient");
                            dispose();
                            Patient_main ah = new Patient_main(patientID);
                            ah.setVisible(true);
                            JOptionPane.showMessageDialog(Login_Button, "You have successfully logged in");
                        } 
                        else {
                            JOptionPane.showMessageDialog(Login_Button, "Wrong Username & Password.");
                        }
                    } catch (SQLException sqlException) {
                        sqlException.printStackTrace();
                    }
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed
        this.setVisible(false);
        Register f;
        f = new Register();
        f.setVisible(true);
        
    }//GEN-LAST:event_Register_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JTextField Pass;
    private javax.swing.JButton Register_Button;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
