/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class order_page extends javax.swing.JFrame {

    /**
     * Creates new form order_page
     */
    public order_page() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public order_page(String drugName, String patientID) {
        initComponents();
        this.setLocationRelativeTo(null);
        Drug_name2.setText(drugName);
        this.patient_id.setText(patientID);
        this.patient_id.setVisible(false);
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try { 
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                            + "user=root&password=root");
            String sql= "Select drugs_name, drugs_quantity, drugs_price from ph_drugs where drugs_name=? ";
            ps = con.prepareStatement(sql);
            ps.setString(1, drugName);
            rs = ps.executeQuery();
            if (rs.next()) {
                float price = rs.getFloat("drugs_price");
                this.Drug_price2.setText( Float.toString( price ) );
                int quantity = rs.getInt("drugs_quantity");
                SpinnerModel model = new SpinnerNumberModel(1, 1, quantity, 1);
                this.drug_quantity.setModel(model);
            } 
            else {
                JOptionPane.showMessageDialog(this, "Error connecting to db");
            }
        } 
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Drug_name2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Drug_price2 = new javax.swing.JLabel();
        Back_btn2 = new javax.swing.JButton();
        Logout_btn2 = new javax.swing.JButton();
        Order_btn2 = new javax.swing.JButton();
        drug_quantity = new javax.swing.JSpinner();
        patient_id = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Drug name :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        Drug_name2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Drug_name2.setForeground(new java.awt.Color(255, 255, 255));
        Drug_name2.setText("jLabel5");
        jPanel3.add(Drug_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Drug price :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        Drug_price2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Drug_price2.setForeground(new java.awt.Color(255, 255, 255));
        Drug_price2.setText("jLabel4");
        jPanel3.add(Drug_price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 30));

        Back_btn2.setBackground(new java.awt.Color(0, 102, 102));
        Back_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back_btn2.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn2.setText("Back");
        Back_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel3.add(Back_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 40));

        Logout_btn2.setBackground(new java.awt.Color(0, 102, 102));
        Logout_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout_btn2.setForeground(new java.awt.Color(255, 255, 255));
        Logout_btn2.setText("Logout");
        Logout_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });
        jPanel3.add(Logout_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 90, 40));

        Order_btn2.setBackground(new java.awt.Color(0, 102, 102));
        Order_btn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Order_btn2.setForeground(new java.awt.Color(255, 255, 255));
        Order_btn2.setText("Order");
        Order_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(Order_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 100, 40));

        drug_quantity.setModel(new javax.swing.SpinnerNumberModel());
        jPanel3.add(drug_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 50, 30));

        patient_id.setText("patient_id");
        jPanel3.add(patient_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Patient_main f = new Patient_main();
        f.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    private void Order_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_btn2ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                               + "user=root&password=root");
            String sql = "insert into patient_orders (patient_idpatient, drugs_name, orders_quantity, orders_date)"
                    + " values( ?, ?, ?, ? )";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, patient_id.getText());
            ps.setString(2, Drug_name2.getText());
            int drugQuantity = (Integer) drug_quantity.getValue();
            ps.setInt(3, drugQuantity);
            LocalDateTime todayDatetime = LocalDateTime.now();
            LocalDate todayDate = todayDatetime.toLocalDate();
            ps.setObject(4, todayDate);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully ordered.");
            Patient_main page = new Patient_main(patient_id.getText());
            page.setVisible(true);
            this.setVisible(false);
        }
        catch (SQLException sqlException) {
                sqlException.printStackTrace();
            }
    }//GEN-LAST:event_Order_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn2;
    private javax.swing.JLabel Drug_name2;
    private javax.swing.JLabel Drug_price2;
    private javax.swing.JButton Logout_btn2;
    private javax.swing.JButton Order_btn2;
    private javax.swing.JSpinner drug_quantity;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel patient_id;
    // End of variables declaration//GEN-END:variables
}
