/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Ahmed
 */
public class patient_communication extends javax.swing.JFrame {
    DefaultTableModel StoreData;
    /**
     * Creates new form patient_communication
     */
    public patient_communication() {
        initComponents();
        this.setLocationRelativeTo(null);
        StoreData = new DefaultTableModel();
        StoreData.addColumn("Order_id");
        StoreData.addColumn("Patient_name");
        StoreData.addColumn("Ordered_drug");
        StoreData.addColumn("Drug_quantity");
        StoreData.addColumn("Order_date");
        
        String patientName = "", orderedDrug;
        Object orderDate;
        int drugQuantity, orderID;
        
        try { 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                            + "user=root&password=root");
            String sql = "select * from patient_orders";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()){
                int patientID = rs.getInt("patient_idpatient");
                
                //get patient name from id 
                sql = "select patient_name from patient where idpatient = ? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, patientID);
                ResultSet patientSet = ps.executeQuery();
                if (patientSet.next())
                    patientName = patientSet.getString("patient_name");
                else
                    JOptionPane.showMessageDialog(this, "error getting patient name");

                
                orderedDrug = rs.getString("drugs_name");
                drugQuantity = rs.getInt("orders_quantity");
                orderDate = rs.getObject("orders_date");
                orderID = rs.getInt("idorders");
                
                Object[] arr = new Object[]{orderID, patientName, orderedDrug, drugQuantity, orderDate} ;
                StoreData.addRow(arr);
                
            }
        } 
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        
        Patient_comm_tb.setModel(StoreData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Patient_comm_tb = new javax.swing.JTable();
        perform_selec_btn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("patient communication");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patient_comm_tb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Patient_comm_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Patient_comm_tb);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 150));

        perform_selec_btn.setBackground(new java.awt.Color(0, 102, 102));
        perform_selec_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perform_selec_btn.setForeground(new java.awt.Color(255, 255, 255));
        perform_selec_btn.setText("Perform the selected Order");
        perform_selec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perform_selec_btnActionPerformed(evt);
            }
        });
        jPanel1.add(perform_selec_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 250, 40));

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 110, 40));

        back.setBackground(new java.awt.Color(0, 102, 102));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 630, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pharmacist f = new pharmacist();
        f.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void perform_selec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perform_selec_btnActionPerformed
        // TODO add your handling code here:
        int r =Patient_comm_tb.getSelectedRow();
        
        String  orderIDstr = Patient_comm_tb.getValueAt(r, 0).toString();
        int orderID = Integer.parseInt(orderIDstr);
        
        String orderedDrug = Patient_comm_tb.getValueAt(r, 2).toString();
        
        String drugQuantitystr =  Patient_comm_tb.getValueAt(r, 3).toString();
        int drugQuantity = Integer.parseInt(drugQuantitystr);
        try{
        // 1) decrement quantity in ph_drugs table
            // UPDATE ph_drugs SET drugs_quantity = drugs_quantity-? WHERE drugs_name=? and drugs_quantity > 0 

            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                        + "user=root&password=root");
            String sql = "UPDATE ph_drugs SET drugs_quantity =drugs_quantity-'"+ drugQuantity +"' WHERE drugs_name= '"+ orderedDrug +"' and drugs_quantity > 0 ";
            Statement stmt = c.createStatement();
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "Pharmacy data updated.");
        // 2) delete this row in patient orders table
         // DELETE from patient_orders where idorders = ?
            
            sql = "DELETE from patient_orders where idorders= '"+ orderID +"' ";
            stmt.executeUpdate(sql);
            
            if(Patient_comm_tb.getSelectedRow() != -1) {
               // remove selected row from the model
                StoreData.removeRow(Patient_comm_tb.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Operation done successfully.");
            }
        }
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }   
        
    }//GEN-LAST:event_perform_selec_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_communication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JTable Patient_comm_tb;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton perform_selec_btn;
    // End of variables declaration//GEN-END:variables
}
