/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Ahmed
 */
public class Patient_main extends javax.swing.JFrame {
    /**
     * Creates new form Patient_main
     */
    public Patient_main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Patient_main(String patientID) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.patient_id.setText(patientID);
        this.patient_id.setVisible(false);
        this.searched.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Search_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Search_btn = new javax.swing.JButton();
        Order_btn = new javax.swing.JButton();
        searched = new javax.swing.JLabel();
        patient_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient main");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setLayout(null);

        Search_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Search_txt);
        Search_txt.setBounds(137, 19, 200, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 60, 30);

        Search_btn.setBackground(new java.awt.Color(0, 102, 102));
        Search_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search_btn.setForeground(new java.awt.Color(255, 255, 255));
        Search_btn.setText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Search_btn);
        Search_btn.setBounds(270, 140, 100, 40);

        Order_btn.setBackground(new java.awt.Color(0, 102, 102));
        Order_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Order_btn.setForeground(new java.awt.Color(255, 255, 255));
        Order_btn.setText("Order");
        Order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Order_btn);
        Order_btn.setBounds(30, 140, 100, 40);

        searched.setForeground(new java.awt.Color(255, 255, 255));
        searched.setText("availability");
        jPanel1.add(searched);
        searched.setBounds(150, 80, 60, 14);

        patient_id.setText("patient_id");
        jPanel1.add(patient_id);
        patient_id.setBounds(10, 10, 70, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 390, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_btnActionPerformed
        // TODO add your handling code here:
        String drugName = Search_txt.getText();
        String patientID = patient_id.getText();
        if (searched.getText() == "available"){
            new order_page(drugName, patientID).setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Cant order not available drug");
        }
    }//GEN-LAST:event_Order_btnActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        // TODO add your handling code here:
        if (Search_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(Order_btn, "Search field cannot be empty.");
        }
        else {
            String searchedDrug = Search_txt.getText();
            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            try { 
                    con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                                   + "user=root&password=root");
                    String sql= "Select drugs_name, drugs_quantity, drugs_price from ph_drugs where drugs_name=?";
                    ps = con.prepareStatement(sql);
                    ps.setString(1, searchedDrug);
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        int quantity = rs.getInt("drugs_quantity");
                        if (quantity > 0){
                            JOptionPane.showMessageDialog(this,searchedDrug + " is available with quantity of : '" + quantity + "' " );
                            searched.setText("available");
                        }
                        else{
                            JOptionPane.showMessageDialog(this,searchedDrug + " is not available");
                            searched.setText("non-available");
                        }
                    } 
                    else {
                        JOptionPane.showMessageDialog(Search_btn, "There is no drug with this name.");
                        searched.setText("non-available");
                    }
            } 
            catch (SQLException sqlException) {
                sqlException.printStackTrace();
            }
        }
    }//GEN-LAST:event_Search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Order_btn;
    private javax.swing.JButton Search_btn;
    private javax.swing.JTextField Search_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patient_id;
    private javax.swing.JLabel searched;
    // End of variables declaration//GEN-END:variables
}
