/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name_field = new javax.swing.JTextField();
        Username_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Age_field = new javax.swing.JTextField();
        Male_rdb = new javax.swing.JRadioButton();
        Female_rdb = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        pass_filed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 45, 22);

        Name_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(Name_field);
        Name_field.setBounds(140, 30, 181, 30);

        Username_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Username_field);
        Username_field.setBounds(140, 180, 181, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 78, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 130, 30, 22);

        Age_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Age_field);
        Age_field.setBounds(140, 130, 181, 30);

        buttonGroup1.add(Male_rdb);
        Male_rdb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Male_rdb.setForeground(new java.awt.Color(255, 255, 255));
        Male_rdb.setText("Male");
        jPanel1.add(Male_rdb);
        Male_rdb.setBounds(160, 290, 61, 31);

        buttonGroup1.add(Female_rdb);
        Female_rdb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Female_rdb.setForeground(new java.awt.Color(255, 255, 255));
        Female_rdb.setText("Female");
        jPanel1.add(Female_rdb);
        Female_rdb.setBounds(240, 290, 81, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 290, 56, 22);

        Register.setBackground(new java.awt.Color(0, 102, 102));
        Register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register);
        Register.setBounds(150, 380, 95, 31);

        pass_filed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(pass_filed);
        pass_filed.setBounds(140, 230, 181, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 230, 90, 22);

        address_field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(address_field);
        address_field.setBounds(140, 80, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 70, 80, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 420, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
       if (Name_field.getText().isEmpty() || Username_field.getText().isEmpty() || Age_field.getText().isEmpty() || pass_filed.getText().isEmpty() )
           JOptionPane.showMessageDialog(Register, "Please, fill all fields.");
       else {
        String Name = Name_field.getText();
        String Username = Username_field.getText();
        String Address = address_field.getText();
        int Age = Integer.parseInt(Age_field.getText());
        String pass = pass_filed.getText();
        String gender ;
        if (Male_rdb.isSelected() == true)
              gender = "male";
         else
             gender = "female";
        // check for pharmacy and store accounts duplication
        if (Username == "1" || Username == "2"){
            JOptionPane.showMessageDialog(Register, "Username already exists.");
            return;
       }
        
        try { 
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                           + "user=root&password=root");
            Statement stmt = c.createStatement();
            
            //check if Username exists
            String sql ;
            sql = "select Patient_UserName from patient where Patient_UserName= '" + Username + "' ";
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()){
                JOptionPane.showMessageDialog(Register, "Username already exists.");
                return;
            }
            else{
                sql= "INSERT INTO patient "
                        + "(patient_name, patient_age, patient_address, Patient_UserName, Patient_Password, Patient_gender)"
                        + " VALUES ( '"+Name+"','"+Age+"', '"+Address+"', '"+Username+"', '"+ pass +"', '"+gender+"' ) ";
               // String sql = "insert into patient values(,'ahmed', 21, 'aa', 'root', 'root', 'male' )";

                stmt.executeUpdate(sql);
                c.close();
                JOptionPane.showMessageDialog(Register, "Successfully registered");
            }
            } 
        catch (SQLException sqlException) {
                    sqlException.printStackTrace();
            }
        this.setVisible(false);
        Login f = new Login();
        f.setVisible(true);
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void Name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_field;
    private javax.swing.JRadioButton Female_rdb;
    private javax.swing.JRadioButton Male_rdb;
    private javax.swing.JTextField Name_field;
    private javax.swing.JButton Register;
    private javax.swing.JTextField Username_field;
    private javax.swing.JTextField address_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField pass_filed;
    // End of variables declaration//GEN-END:variables
}
