/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Ahmed
 */
public class service extends javax.swing.JFrame {

    /**
     * Creates new form service
     */
    public service() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add_medicine = new javax.swing.JButton();
        Check_requests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store service");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add_medicine.setBackground(new java.awt.Color(0, 102, 102));
        Add_medicine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add_medicine.setForeground(new java.awt.Color(255, 255, 255));
        Add_medicine.setText("Add medicine");
        Add_medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_medicineActionPerformed(evt);
            }
        });
        jPanel1.add(Add_medicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 40));

        Check_requests.setBackground(new java.awt.Color(0, 102, 102));
        Check_requests.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Check_requests.setForeground(new java.awt.Color(255, 255, 255));
        Check_requests.setText("Check requests");
        Check_requests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_requestsActionPerformed(evt);
            }
        });
        jPanel1.add(Check_requests, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_medicineActionPerformed
        this.setVisible(false);
        Add_medicine f = new Add_medicine();
        f.setVisible(true);
    }//GEN-LAST:event_Add_medicineActionPerformed

    private void Check_requestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_requestsActionPerformed
        this.setVisible(false);
        store_check_requests f = new store_check_requests();
        f.setVisible(true);
    }//GEN-LAST:event_Check_requestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_medicine;
    private javax.swing.JButton Check_requests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
