/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Ahmed
 */
public class store_order_page extends javax.swing.JFrame {

    /**
     * Creates new form store_order_page
     */
    public store_order_page() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public store_order_page(String drugName) {
       initComponents();
       this.setLocationRelativeTo(null);
       Drug_name.setText(drugName);
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try { 
            con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                            + "user=root&password=root");
            String sql= "Select drugs_name, drugs_quantity, drugs_price from store_drugs where drugs_name=? ";
            ps = con.prepareStatement(sql);
            ps.setString(1, drugName);
            rs = ps.executeQuery();
            if (rs.next()) {
                float price = rs.getFloat("drugs_price");
                this.Drug_price.setText( Float.toString( price ) );
                int quantity = rs.getInt("drugs_quantity");
                SpinnerModel model = new SpinnerNumberModel(1, 1, quantity, 1);
                this.Drug_quantity.setModel(model);
            } 
            else {
                JOptionPane.showMessageDialog(this, "Error connecting to db");
            }
        } 
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Drug_name = new javax.swing.JLabel();
        Drug_price = new javax.swing.JLabel();
        Order = new javax.swing.JButton();
        Exit_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        Drug_quantity = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store order");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Drug name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Drug price  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity    :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        Drug_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Drug_name.setForeground(new java.awt.Color(255, 255, 255));
        Drug_name.setText("jLabel4");
        jPanel1.add(Drug_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        Drug_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Drug_price.setForeground(new java.awt.Color(255, 255, 255));
        Drug_price.setText("jLabel5");
        jPanel1.add(Drug_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        Order.setBackground(new java.awt.Color(0, 102, 102));
        Order.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Order.setForeground(new java.awt.Color(255, 255, 255));
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });
        jPanel1.add(Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, 40));

        Exit_btn.setBackground(new java.awt.Color(0, 102, 102));
        Exit_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        Exit_btn.setText("Logout");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 120, 40));

        Back_btn.setBackground(new java.awt.Color(0, 102, 102));
        Back_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 40));

        Drug_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Drug_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        store_communication f = new store_communication();
        f.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                               + "user=root&password=root");
            String sql = "insert into pharmacy_orders ( drugs_name, orders_quantity, orders_date)"
                    + " values( ?, ?, ? )";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, Drug_name.getText());
            int drugQuantity = (Integer) Drug_quantity.getValue();
            ps.setInt(2, drugQuantity);
            LocalDateTime todayDatetime = LocalDateTime.now();
            LocalDate todayDate = todayDatetime.toLocalDate();
            ps.setObject(3, todayDate);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully ordered.");
            store_communication page = new store_communication();
            page.setVisible(true);
            this.setVisible(false);
        }
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }//GEN-LAST:event_OrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store_order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store_order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store_order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store_order_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store_order_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel Drug_name;
    private javax.swing.JLabel Drug_price;
    private javax.swing.JSpinner Drug_quantity;
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton Order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
