/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class store_check_requests extends javax.swing.JFrame {
    DefaultTableModel StoreData;
    /**
     * Creates new form store_check_requests
     */
    public store_check_requests() {
        initComponents();
        this.setLocationRelativeTo(null);
        StoreData = new DefaultTableModel();
        StoreData.addColumn("Order_id");
        StoreData.addColumn("Ordered_drug");
        StoreData.addColumn("Drug_quantity");
        StoreData.addColumn("Order_date");
        
        String  orderedDrug;
        Object orderDate;
        int drugQuantity, orderID;
        
        try { 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                            + "user=root&password=root");
            String sql = "select * from pharmacy_orders";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()){
                
                
                orderedDrug = rs.getString("drugs_name");
                drugQuantity = rs.getInt("orders_quantity");
                orderDate = rs.getObject("orders_date");
                orderID = rs.getInt("pharmacy_ordersID");
                
                Object[] arr = new Object[]{orderID, orderedDrug, drugQuantity, orderDate} ;
                StoreData.addRow(arr);
                
            }
        } 
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        
        Requests_dt.setModel(StoreData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Requests_dt = new javax.swing.JTable();
        request_checked_btn = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check requests");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Requests_dt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Requests_dt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Requests_dt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 150));

        request_checked_btn.setBackground(new java.awt.Color(0, 102, 102));
        request_checked_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        request_checked_btn.setForeground(new java.awt.Color(255, 255, 255));
        request_checked_btn.setText("Check request");
        request_checked_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request_checked_btnActionPerformed(evt);
            }
        });
        jPanel1.add(request_checked_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 40));

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.setVisible(false);
        Login f = new Login();
        f.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void request_checked_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request_checked_btnActionPerformed
        // TODO add your handling code here:
        int r =Requests_dt.getSelectedRow();
        
        String  orderIDstr = Requests_dt.getValueAt(r, 0).toString();
        int orderID = Integer.parseInt(orderIDstr);
        
        String orderedDrug = Requests_dt.getValueAt(r, 1).toString();
        
        String drugQuantitystr =  Requests_dt.getValueAt(r, 2).toString();
        int drugQuantity = Integer.parseInt(drugQuantitystr);
        try{
        // 1) decrement quantity in ph_drugs table
            // UPDATE store_drugs SET drugs_quantity = drugs_quantity-? WHERE drugs_name=? and drugs_quantity > 0 

            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                        + "user=root&password=root");
            String sql = "UPDATE store_drugs SET drugs_quantity =drugs_quantity-'"+ drugQuantity +"' WHERE drugs_name= '"+ orderedDrug +"' and drugs_quantity > 0 ";
            Statement stmt = c.createStatement();
            stmt.executeUpdate(sql);
        
            JOptionPane.showMessageDialog(this, "Store data updated.");
        // 2) delete this row in patient orders table
         // DELETE from ph_orders where idorders = ?
            
            sql = "DELETE from store_orders where pharmacy_ordersID= '"+ orderID +"' ";
            stmt.executeUpdate(sql);
            
            if(Requests_dt.getSelectedRow() != -1) {
               // remove selected row from the model
                StoreData.removeRow(Requests_dt.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Operation done successfully.");
            }
        }
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }//GEN-LAST:event_request_checked_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store_check_requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store_check_requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store_check_requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store_check_requests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store_check_requests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JTable Requests_dt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton request_checked_btn;
    // End of variables declaration//GEN-END:variables
}
