/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public class store_communication extends javax.swing.JFrame {

    /**
     * Creates new form store_communication
     */
    public store_communication() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.searched.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Search_btn = new javax.swing.JButton();
        Search_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searched = new javax.swing.JLabel();
        Order_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store commcunication");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/icon.png")).getImage()
        );
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_btn.setBackground(new java.awt.Color(0, 102, 102));
        Search_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search_btn.setForeground(new java.awt.Color(255, 255, 255));
        Search_btn.setText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 130, 40));

        Search_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(Search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, 30));

        searched.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searched.setForeground(new java.awt.Color(255, 255, 255));
        searched.setText("Availability");
        jPanel2.add(searched, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 90, 30));

        Order_btn.setBackground(new java.awt.Color(0, 102, 102));
        Order_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Order_btn.setForeground(new java.awt.Color(255, 255, 255));
        Order_btn.setText("Order");
        Order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/WhatsApp Image 2021-12-29 at 5.07.14 PM.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_btnActionPerformed
        // TODO add your handling code here:
        String drugName = Search_txt.getText();
        if (searched.getText() == "available"){
            new store_order_page(drugName).setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Cant order not available drug");
        }
    }//GEN-LAST:event_Order_btnActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        // TODO add your handling code here:
        if (Search_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Search field cannot be empty.");
        }
        else {
            String searchedDrug = Search_txt.getText();
            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;
            try { 
                con = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy?"
                                               + "user=root&password=root");
                String sql= "Select drugs_name, drugs_quantity, drugs_price from store_drugs where drugs_name=?";
                ps = con.prepareStatement(sql);
                ps.setString(1, searchedDrug);
                rs = ps.executeQuery();
                if (rs.next()) {
                    int quantity = rs.getInt("drugs_quantity");
                    if (quantity > 0){
                        JOptionPane.showMessageDialog(this,searchedDrug + " is available with quantity of : '" + quantity + "' " );
                        searched.setText("available");
                    }
                    else{
                        JOptionPane.showMessageDialog(this,searchedDrug + " is not available");
                        searched.setText("non-available");
                    }
                } 
                else {
                    JOptionPane.showMessageDialog(this, "There is no drug with this name.");
                    searched.setText("non-available");
                }
            } 
            catch (SQLException sqlException) {
                sqlException.printStackTrace();
            }
        }
    }//GEN-LAST:event_Search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(store_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(store_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(store_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(store_communication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new store_communication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Order_btn;
    private javax.swing.JButton Search_btn;
    private javax.swing.JTextField Search_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel searched;
    // End of variables declaration//GEN-END:variables
}
